spring:
  application:
    name: Repository
  profiles:
    default: local
    group:
      local:
        - auth
        - database
        - wallet
        - jasypt
        - logging
        - spring-docs
      sample:
        - auth
        - database
        - wallet
        - jasypt
        - logging
        - spring-docs
  jackson:
    default-property-inclusion: non_null

server:
  port: 8098
  servlet:
    context-path: /lss
